package com.shanlin.model;

import java.io.Serializable;

public class Application implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_id
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_key
     *
     * @mbg.generated
     */
    private Long appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_secrect
     *
     * @mbg.generated
     */
    private String appSecrect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_id
     *
     * @return the value of application.app_id
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_id
     *
     * @param appId the value for application.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_name
     *
     * @return the value of application.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_name
     *
     * @param appName the value for application.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_key
     *
     * @return the value of application.app_key
     *
     * @mbg.generated
     */
    public Long getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_key
     *
     * @param appKey the value for application.app_key
     *
     * @mbg.generated
     */
    public void setAppKey(Long appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_secrect
     *
     * @return the value of application.app_secrect
     *
     * @mbg.generated
     */
    public String getAppSecrect() {
        return appSecrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_secrect
     *
     * @param appSecrect the value for application.app_secrect
     *
     * @mbg.generated
     */
    public void setAppSecrect(String appSecrect) {
        this.appSecrect = appSecrect == null ? null : appSecrect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appId=").append(appId);
        sb.append(", appName=").append(appName);
        sb.append(", appKey=").append(appKey);
        sb.append(", appSecrect=").append(appSecrect);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}